<?
$aMenuLinks = Array(
	Array(
		"О разделе", 
		"/personal/my/", 
		Array(), 
		Array(), 
		"CSite::InGroup(array(1,5))" 
	),
	Array(
		"Мой профиль", 
		"/personal/profile", 
		Array(), 
		Array(), 
		"CSite::InGroup(array(1,5))" 
	),
	Array(
		"Компании", 
		"/personal/my/firms/", 
		Array(), 
		Array(), 
		"CSite::InGroup(array(1,5))" 
	),
	Array(
		"Статьи", 
		"/personal/my/articles/", 
		Array(), 
		Array(), 
		"CSite::InGroup(array(1,5))" 
	),
	Array(
		"Видео", 
		"/personal/my/video/", 
		Array(), 
		Array(), 
		"CSite::InGroup(array(1,5))" 
	)
);
?>